In [ ]:
import torch
import torch.nn as nn

In [ ]:
 # we need to inherit it from a base class
class Model(nn.Module):
  def __init__(self, input_features):
    super().__init__()
    self.linear = nn.Linear(input_features, 1) # i/p , o/p
    self.sigmoid = nn.Sigmoid()


  def forward(self, features):  # calculate o/p when features are passed in forward pass
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [ ]:
# create dataset
features = torch.rand(10,5)

# create model
torch.manual_seed(32)
model = Model(features.shape[1])

# call model for forward pass

# model.forward(features) # can do this but pytorch recommends to use this
# as magic method __call__ is overwritten by fun that whenever a obj of this class is called forward method is autometiclally triggered
model(features)


tensor([[0.6780],
        [0.6089],
        [0.6372],
        [0.6056],
        [0.6314],
        [0.6617],
        [0.6321],
        [0.6888],
        [0.5605],
        [0.5645]], grad_fn=<SigmoidBackward0>)

In [ ]:
# show weights
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[ 0.0885, -0.1874, -0.2128,  0.2955,  0.1812]], requires_grad=True)
Parameter containing:
tensor([0.4293], requires_grad=True)


In [ ]:
!pip install torchinfo
from torchinfo import summary

summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
class Model(nn.Module):
  def __init__(self, input_features):

    super().__init__()
    self.layer1 = nn.Linear(input_features, 3)
    self.relu = nn.ReLU()
    self.layer2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.layer1(features)
    out = self.relu(out)
    out = self.layer2(out)
    out = self.sigmoid(out)

    return out;


# Example:
features = torch.rand(10, 5)  # batch_size = 10, input_features = 5

In [ ]:
torch.manual_seed(42)
# Create model
model1 = Model(input_features=5)

In [ ]:
# Call the forward_pass directly
output = model1(features)

In [ ]:
print("Output:", output)

Output: tensor([[0.4451],
        [0.4404],
        [0.4267],
        [0.4730],
        [0.4470],
        [0.4408],
        [0.4408],
        [0.4206],
        [0.4670],
        [0.4409]], grad_fn=<SigmoidBackward0>)


In [ ]:
print("Layer 1 weights:", model1.layer1.weight)
print("Layer 1 bias:", model1.layer1.bias)

Layer 1 weights: Parameter containing:
tensor([[ 0.3419,  0.3712, -0.1048,  0.4108, -0.0980],
        [ 0.0902, -0.2177,  0.2626,  0.3942, -0.3281],
        [ 0.3887,  0.0837,  0.3304,  0.0606,  0.2156]], requires_grad=True)
Layer 1 bias: Parameter containing:
tensor([-0.0631,  0.3448,  0.0661], requires_grad=True)


In [ ]:
print("Layer 2 weights:", model1.layer2.weight)
print("Layer 2 bias:", model1.layer2.bias)

Layer 2 weights: Parameter containing:
tensor([[-0.2695,  0.1472, -0.2660]], requires_grad=True)
Layer 2 bias: Parameter containing:
tensor([-0.0677], requires_grad=True)


In [ ]:
from torchinfo import summary
summary(model1, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [ ]:
# super().__init__()
# self.network= nn.Sequential(
#     nn.Linear(input_features),
#     nn.ReLU(),
#     nn.Linear(num_features,3),
#     nn.Sigmoid()
# )

# def forward(self, features):
#   output = self.network(features)
#   return output