In [27]:
import torch
if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

Tesla T4


In [28]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [29]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [30]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0    ...          17.33           184.60      2019.0           0.16220   
1    ...          23.41           158.80      1956.0           0.12380   
2    ...          25.53           152.50      1709.0           0.14440   
3    ...          26.50            98.87       567.7           0.20980   
4    ...          16.67           152.20      1575.0           0.13740   
..   ...            ...              ...         ...               ...   
564  ...          26.40           166.10      2027.0           0.14100   
565  ...          38.25           155.00      1731.0           0.11660   
566  ...          34.12           126.70      1124.0           0.11390   
567  ...          39.42           184.60      1821.0           0.16500   
568  ...          30.37            59.16       268.6           0.08996   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0              0.66560           0.7119                0.2654          0.4601   
1              0.18660           0.2416                0.1860          0.2750   
2              0.42450           0.4504                0.2430          0.3613   
3              0.86630           0.6869                0.2575          0.6638   
4              0.20500           0.4000                0.1625          0.2364   
..                 ...              ...                   ...             ...   
564            0.21130           0.4107                0.2216          0.2060   
565            0.19220           0.3215                0.1628          0.2572   
566            0.30940           0.3403                0.1418          0.2218   
567            0.86810           0.9387                0.2650          0.4087   
568            0.06444           0.0000                0.0000          0.2871   

     fractal_dimension_worst  Unnamed: 32  
0                    0.11890          NaN  
1                    0.08902          NaN  
2                    0.08758          NaN  
3                    0.17300          NaN  
4      

In [31]:
df.shape

(569, 33)

In [32]:
df.drop(columns =['id','Unnamed: 32'], inplace = True)

In [33]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [34]:
X_train, X_test, y_train, y_pred = train_test_split(df.iloc[:,1:], df.iloc[:,0],test_size=0.2)

In [35]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [36]:
X_train

array([[-0.362373  , -1.44303115, -0.37802191, ...,  0.02555949,
        -0.81948566,  0.11919344],
       [-1.26714445, -0.04381893, -1.27975105, ..., -1.15306499,
        -0.5432754 , -0.22941787],
       [ 1.44033498, -0.83407168,  1.42295114, ...,  0.97714883,
        -0.72037492, -1.14858417],
       ...,
       [-1.12560482, -0.4645123 , -1.11116871, ..., -0.88854763,
         0.27398201,  0.25357126],
       [ 1.74505813,  0.81383773,  1.67561755, ...,  0.66505201,
         1.30408379,  0.01730862],
       [-1.46165465, -1.19200969, -1.47401424, ..., -1.52895808,
         0.16999697, -0.2933024 ]])

In [37]:
 y_train

322    B
548    B
161    M
526    B
225    B
      ..
500    B
305    B
222    B
95     M
307    B
Name: diagnosis, Length: 455, dtype: object

## label encoding

In [38]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_pred)

In [39]:
y_train

array([0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0,

## numpy array to pytorch tensors

In [40]:
X_train.shape

(455, 30)

In [41]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [42]:
X_train_tensor

tensor([[-0.3624, -1.4430, -0.3780,  ...,  0.0256, -0.8195,  0.1192],
        [-1.2671, -0.0438, -1.2798,  ..., -1.1531, -0.5433, -0.2294],
        [ 1.4403, -0.8341,  1.4230,  ...,  0.9771, -0.7204, -1.1486],
        ...,
        [-1.1256, -0.4645, -1.1112,  ..., -0.8885,  0.2740,  0.2536],
        [ 1.7451,  0.8138,  1.6756,  ...,  0.6651,  1.3041,  0.0173],
        [-1.4617, -1.1920, -1.4740,  ..., -1.5290,  0.1700, -0.2933]],
       dtype=torch.float64)

In [43]:
y_train_tensor.shape

torch.Size([455])

## defining Model

In [44]:
class SimpleNN():

  def __init__(self, X):
    self.weights = torch.rand(X.shape[1] , 1, dtype = torch.float64, requires_grad=True)
    self.bias = torch.zeros(1, dtype= torch.float64, requires_grad=True)

  def forward(self,X):
    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1-epsilon)

    # calculate loss
    loss = - (y * torch.log(y_pred) + (1-y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss


## import parameters

In [45]:
learning_rate = 0.1
epochs = 25

## Training Pipeline

In [49]:
# creating model

model = SimpleNN(X_train_tensor)
model.weights

# define loop
for epoch in range(epochs):

# Forward pass
  y_pred = model.forward(X_train_tensor)
  # print(y_pred)

  # calculate loss
  loss = model.loss_function(y_pred, y_train_tensor)
  print(f"Epoch:{epoch + 1}, Loss: {loss.item()}")

  # backward pass
  loss.backward()

  # update parameters with gradients off
  with torch.no_grad():
    model.weights-=learning_rate * model.weights.grad
    model.bias-=learning_rate * model.bias.grad

  # zero gradients for not accumulating
  model.weights.grad.zero_()
  model.bias.grad.zero_()

Epoch:1, Loss: 3.569080022687671
Epoch:2, Loss: 3.4421304959714636
Epoch:3, Loss: 3.310691215388097
Epoch:4, Loss: 3.1746231754207557
Epoch:5, Loss: 3.0292647705571483
Epoch:6, Loss: 2.8731445253682857
Epoch:7, Loss: 2.7148498913707475
Epoch:8, Loss: 2.552603613512073
Epoch:9, Loss: 2.385636108013653
Epoch:10, Loss: 2.2167528807518613
Epoch:11, Loss: 2.0493745413616913
Epoch:12, Loss: 1.8852511326369246
Epoch:13, Loss: 1.720357586052158
Epoch:14, Loss: 1.560766555693364
Epoch:15, Loss: 1.407882165437894
Epoch:16, Loss: 1.2668097243604903
Epoch:17, Loss: 1.1424298136056825
Epoch:18, Loss: 1.036756558867737
Epoch:19, Loss: 0.9508654082427558
Epoch:20, Loss: 0.8844284093113416
Epoch:21, Loss: 0.8355469368205511
Epoch:22, Loss: 0.801097439000933
Epoch:23, Loss: 0.7774794260602866
Epoch:24, Loss: 0.7613644056232142
Epoch:25, Loss: 0.7501424964950961


In [51]:
model.weights

tensor([[-0.0205],
        [-0.1676],
        [ 0.2467],
        [ 0.4139],
        [ 0.0253],
        [ 0.0191],
        [ 0.2260],
        [ 0.2495],
        [-0.2955],
        [ 0.6687],
        [ 0.2575],
        [ 0.0727],
        [-0.3962],
        [ 0.1693],
        [ 0.1346],
        [-0.3695],
        [ 0.2456],
        [-0.4473],
        [ 0.0203],
        [ 0.5693],
        [-0.1602],
        [ 0.2362],
        [-0.2884],
        [-0.2496],
        [-0.0639],
        [-0.0045],
        [-0.0703],
        [ 0.2262],
        [ 0.0702],
        [-0.4499]], dtype=torch.float64, requires_grad=True)

In [50]:
model.bias

tensor([-0.1264], dtype=torch.float64, requires_grad=True)

## Evaluation

In [59]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.92).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.6206524968147278


In [47]:
# to calculate accuracy we need to compare with actual labels tat re in 0 1 form
# so we decide threshold of 0.5