# **1. Tensors**


everything in pytorch is based on tensor operations . A tensor is muilti dimensional matrix containing elements of a single datatype.

In [1]:
import torch
print(torch.__version__)

2.6.0+cu124


In [2]:
if torch.cuda.is_available():
  print("GPU is available")
  print(f'Using GPU:{torch.cuda.get_device_name(0)}')
else:
  print("Gpu is not available")

GPU is available
Using GPU:Tesla T4


In [3]:


# torch.empty(size): uninitialised
x = torch.empty(1) # scaler
print("empty(1):", x)
x =torch.empty(3) # vector
print("empty(3):", x)
x = torch.empty(2,3) # matrix
print("empty(2,3):", x)
x = torch.empty(2,2,3) # tensor 3d
# x = torch.empty(2,2,2,3) # tensor 4d
print("empty(2,2,3):",x)

tensor = torch.arange(12)  # A tensor with values [0, 1, 2, ..., 11]
print(tensor)


#torch.rand(size) random numbers [0,1]
x =torch.rand(5, 3)
print("rand(5,3)", x)


# torch.zeros(size), fill with 0
# torch.ones(size), fill with 1
x =torch.zeros(5,3)
print("zeros(5,3)", x)

#  torch.tensor() creates a tensor of default dtype int64

empty(1): tensor([5.0657e+08])
empty(3): tensor([1.9485e-15, 0.0000e+00, 5.0657e+08])
empty(2,3): tensor([[1.9467e-15, 0.0000e+00, 1.9467e-15],
        [0.0000e+00, 0.0000e+00, 4.1877e-38]])
empty(2,2,3): tensor([[[1.9739e-15, 0.0000e+00, 0.0000e+00],
         [2.3510e-38, 1.2530e-18, 0.0000e+00]],

        [[1.0842e-19, 0.0000e+00, 1.3563e-19],
         [1.3563e-19, 1.3563e-19, 1.3563e-19]]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
rand(5,3) tensor([[0.7617, 0.5767, 0.9991],
        [0.6425, 0.5068, 0.5859],
        [0.6570, 0.1552, 0.7416],
        [0.2921, 0.4567, 0.6201],
        [0.9313, 0.0370, 0.8441]])
zeros(5,3) tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [4]:
#other ways

#arange [star,end,jump)
print("using arange", torch.arange(0,10,2))

#using linspace [start,end,no of linearly spaced pts)
print("using linspace", torch.linspace(0,10,10))

#using eye identity matrix
print("using eye",torch.eye(5))

#full
print("using full", torch.full((3,3),5))

using arange tensor([0, 2, 4, 6, 8])
using linspace tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


In [5]:
# for keeping same values

c = torch.rand(5,3)
print(c)
torch.manual_seed(100)
c = torch.rand(5,3)
print(c)

tensor([[0.6336, 0.0638, 0.8866],
        [0.7158, 0.4696, 0.4318],
        [0.6549, 0.2429, 0.3758],
        [0.6588, 0.8170, 0.1887],
        [0.2604, 0.3164, 0.9882]])
tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539],
        [0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356],
        [0.7118, 0.7876, 0.4183]])


In [6]:
#check size
print("size", x.size())  # x.size(0) for accessing specific dimension
print("shape", x.shape) # x.shape[0] for accessing specific dimension

# for creating same shaped tensor with diff values
print(torch.empty_like(x))
print(torch.ones_like(x))
print(torch.zeros_like(x))

# torch.rand_like(x) # wont work as .rand generates floats b/ 0 and 1 so we ve to define explictly
print(torch.rand_like(x, dtype= torch.float32))

size torch.Size([5, 3])
shape torch.Size([5, 3])
tensor([[5.0657e+08, 4.5174e-41, 1.9468e-15],
        [0.0000e+00, 1.9605e-15, 0.0000e+00],
        [1.9796e-15, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.9954e-15, 0.0000e+00],
        [2.1423e-16, 0.0000e+00, 9.9671e+03]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.9014, 0.9969, 0.7565],
        [0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770],
        [0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])


In [7]:
#check dtype

print(x.dtype)

#specify types float32 deafult
x = torch.zeros(5,3, dtype=torch.float16)
y = torch.tensor([[2,3,4],[4,6,7],[8,8,6]], dtype=torch.float32)
print(x)
print(y)

#check dtype
print(x.dtype)
print(y.dtype)

# already existing tensor change datatype
# using to()
y.to(torch.int16)

torch.float32
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
tensor([[2., 3., 4.],
        [4., 6., 7.],
        [8., 8., 6.]])
torch.float16
torch.float32


tensor([[2, 3, 4],
        [4, 6, 7],
        [8, 8, 6]], dtype=torch.int16)

In [8]:
# construct from data
x = torch.tensor([5.5, 3])
print(x, x.dtype)


tensor([5.5000, 3.0000]) torch.float32


In [9]:
# requires_grad argument
# this will tell pytorch that it will need to calculate the gradient for this tensor
# later in your optimization steps
# i.e this is a variable in your model that you want to optimize
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


## **operations with tensors**

In [10]:
x =torch.ones(4,5)
y =torch.rand(4,5)

#elementary addition
z = x + y
torch.add(x,y)

print(x)
print(y)
print(z)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[0.5277, 0.2472, 0.7909, 0.4235, 0.0169],
        [0.2209, 0.9535, 0.7064, 0.1629, 0.8902],
        [0.5163, 0.0359, 0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123, 0.9051, 0.5989]])
tensor([[1.5277, 1.2472, 1.7909, 1.4235, 1.0169],
        [1.2209, 1.9535, 1.7064, 1.1629, 1.8902],
        [1.5163, 1.0359, 1.6476, 1.3430, 1.3182],
        [1.5261, 1.0447, 1.5123, 1.9051, 1.5989]])


**in place addition, everything with a trailing underscore is inplace operation
i.e it will modify the variable**

In [11]:
# result is stored in y only so that new space is not occupied
y.add_(x)
print(y)

tensor([[1.5277, 1.2472, 1.7909, 1.4235, 1.0169],
        [1.2209, 1.9535, 1.7064, 1.1629, 1.8902],
        [1.5163, 1.0359, 1.6476, 1.3430, 1.3182],
        [1.5261, 1.0447, 1.5123, 1.9051, 1.5989]])


In [12]:
torch.relu(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [13]:
x.relu_() # inplace operation

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [14]:
z = x - y
z = torch.sub(x,y)

z = x * y
z = torch.mul(x,y)

z = x / y
z = torch.div(x,y)

#int divison
d = (x * 100)//3
print(d)

#mod
e = (x * 132) % 3
print(e)

#pow
z = x**2
print(z)

print(f"element wise op,{x ** y}")

tensor([[33., 33., 33., 33., 33.],
        [33., 33., 33., 33., 33.],
        [33., 33., 33., 33., 33.],
        [33., 33., 33., 33., 33.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
element wise op,tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [15]:
s = torch.tensor([-2, 4, 67.89 ,5.33 ,7 ,-3.76, -4, -23])

print(torch.abs(s))
print(torch.neg(s))
print(torch.round(s))
print(torch.ceil(s))
print(torch.floor(s))

# clamp numbers between a range
print(torch.clamp(s, min=10, max =20))

tensor([ 2.0000,  4.0000, 67.8900,  5.3300,  7.0000,  3.7600,  4.0000, 23.0000])
tensor([  2.0000,  -4.0000, -67.8900,  -5.3300,  -7.0000,   3.7600,   4.0000,
         23.0000])
tensor([ -2.,   4.,  68.,   5.,   7.,  -4.,  -4., -23.])
tensor([ -2.,   4.,  68.,   6.,   7.,  -3.,  -4., -23.])
tensor([ -2.,   4.,  67.,   5.,   7.,  -4.,  -4., -23.])
tensor([10., 10., 20., 10., 10., 10., 10., 10.])


##**Reduction operation**

In [16]:
g = torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)
g

tensor([[7., 9., 2.],
        [6., 7., 7.]])

In [17]:
# sum of whole tensor
print(torch.sum(g))

# sum along row
print(torch.sum(g, dim=1))

# sum along col
print(torch.sum(g, dim=0))

tensor(38.)
tensor([18., 20.])
tensor([13., 16.,  9.])


In [18]:
print(torch.mean(g)) # mean works on float only
print(torch.mean(g, dim=1))


tensor(6.3333)
tensor([6.0000, 6.6667])


In [19]:
# similarly median , max, min, product, standard diveation, argmax, argmin, etc

print(torch.median(g))
print(torch.max(g))
print(torch.min(g))
print(torch.prod(g))
print(torch.std(g))
print(torch.var(g))
print(torch.argmax(g))  # tells max item position
print(torch.argmin(g))  # tells min item position

tensor(7.)
tensor(9.)
tensor(2.)
tensor(37044.)
tensor(2.3381)
tensor(5.4667)
tensor(1)
tensor(2)


In [20]:
# matrix muiltiplication

a1 = torch.tensor([[5,6,7], [3,4,6]])
a2 = torch.tensor([[3,2,5],[5,9,6],[9,0, 7]])
a2 = a2.to(torch.float32)
a3 = torch.tensor([[3,2],[5,6],[0, 7]])


print(f"matmul: {torch.matmul(a1,a3)}")

# dot product
v1 = torch.tensor([3,5,6])
v2 = torch.tensor([5,6,7])
print(f"dot prod : {torch.dot(v1,v2)}")
print(torch.transpose(a1,0,1))

# determinent
print(torch.det(a2))    # only if sq mat

# inverse
print(torch.inverse(a2)) # only if sq mat

matmul: tensor([[45, 95],
        [29, 72]])
dot prod : 87
tensor([[5, 3],
        [6, 4],
        [7, 6]])
tensor(-178.0000)
tensor([[-0.3539,  0.0787,  0.1854],
        [-0.1067,  0.1348, -0.0393],
        [ 0.4551, -0.1011, -0.0955]])


In [21]:
#comparision operations

# i < j
# i > j
# i != j
# i == j
# i <= j
# i >= j

##special functions

In [22]:
print(torch.log(g))
print(torch.exp(g))
print(torch.sqrt(g))
print(torch.sigmoid(g))
print(torch.softmax(g, dim=0)) # only for float type
print(torch.relu(g))
print(torch.tanh(g))

tensor([[1.9459, 2.1972, 0.6931],
        [1.7918, 1.9459, 1.9459]])
tensor([[1.0966e+03, 8.1031e+03, 7.3891e+00],
        [4.0343e+02, 1.0966e+03, 1.0966e+03]])
tensor([[2.6458, 3.0000, 1.4142],
        [2.4495, 2.6458, 2.6458]])
tensor([[0.9991, 0.9999, 0.8808],
        [0.9975, 0.9991, 0.9991]])
tensor([[0.7311, 0.8808, 0.0067],
        [0.2689, 0.1192, 0.9933]])
tensor([[7., 9., 2.],
        [6., 7., 7.]])
tensor([[1.0000, 1.0000, 0.9640],
        [1.0000, 1.0000, 1.0000]])


##**slicing**

In [23]:

x = torch.rand(5,3)
print(x)
print("x[:, 0]", x[:, 0]) # all rows col 0
print("x[1, :]", x[1, :]) # row 1 all cols
print("x[1, 1]", x[1, 1]) # element at 1,1

# get actual value if only 1 ele in tensor
print("x[1,1].item()", x[1,1].item())

tensor([[0.6896, 0.3687, 0.9053],
        [0.8356, 0.3039, 0.6726],
        [0.5740, 0.9233, 0.9178],
        [0.7590, 0.7775, 0.6179],
        [0.3379, 0.2170, 0.9454]])
x[:, 0] tensor([0.6896, 0.8356, 0.5740, 0.7590, 0.3379])
x[1, :] tensor([0.8356, 0.3039, 0.6726])
x[1, 1] tensor(0.3039)
x[1,1].item() 0.30390483140945435


In [24]:
# for copying a tesnor w/o change in original tensor
b = a2.clone()
b

tensor([[3., 2., 5.],
        [5., 9., 6.],
        [9., 0., 7.]])

In [25]:
# Reshape with torch.view()

# The torch.view() function in PyTorch is used to reshape a tensor without copying its data. It creates a new view of the original tensor with a different shape, as long as the tensor is contiguous in memory.
# Since view() does not copy data, modifying the reshaped tensor will also affect the original tensor.
# However, if the tensor is not contiguous, you may need to use .contiguous() before calling view().


x = torch.rand(4,3)
y = x.view(12)
z = x.view(-1, 12) # the size -1 is inferred from other dimensions
# if -1 it pytorch will autometically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 3]) torch.Size([12]) torch.Size([1, 12])


In PyTorch, a tensor is contiguous when its elements are stored in memory without gaps, following their expected order. Contiguous tensors allow efficient reshaping and viewing without copying data.


In [26]:
# When you perform operations like transpose() or permute(), PyTorch may rearrange how the tensor is stored in memory
# Even though the tensor looks different,
# the underlying data may no longer be stored in a straightforward, contiguous order.

tensor = torch.arange(12).view(3, 4)  # A 3x4 tensor
transposed = tensor.t()  # Transpose the tensor

print(transposed.is_contiguous())  # Check if it's contiguous (False)

False


In [27]:
# Since .t() changes the memory layout, calling view() directly on transposed will fail. To fix this, you need .contiguous() before using view():
contiguous_tensor = transposed.contiguous().view(4, 3)  # Now it works!


# - Contiguous tensors allow reshaping with .view().
# - Non-contiguous tensors (from operations like .transpose()) need .contiguous() first.
# - .contiguous() creates a copy in a proper memory layout, allowing view() to work.


In [28]:
# - reshape(): Tries to return a view when possible, but if that's not feasible (like when the tensor is not contiguous), it will create a copy.
# - view() never creates a copy—it only works if the tensor is contiguous.
# - If the tensor is not contiguous, view() will fail.
# - .contiguous() does create a copy, making the tensor suitable for view().
# So, if you need reshaping without copying, ensure the tensor is contiguous first. Otherwise, consider using reshape() instead, which can create a copy when needed.


In [29]:
tensor = torch.arange(12).view(3, 4)  # Contiguous tensor
transposed = tensor.t()  # Now it's non-contiguous

print(transposed.is_contiguous())  # False

# Trying view() will fail
try:
    transposed.view(4, 3)
except RuntimeError as e:
    print(f"View failed: {e}")

# Using .contiguous() first will create a copy, allowing view() to work
fixed_tensor = transposed.contiguous().view(4, 3)
print(f"Fixed tensor:\n{fixed_tensor}")

False
Fixed tensor:
tensor([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])


In [30]:
tensor.flatten()

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [31]:
f = torch.rand(2,3,4)
f

tensor([[[0.0103, 0.9516, 0.2855, 0.2324],
         [0.9141, 0.7668, 0.1659, 0.4393],
         [0.2243, 0.8935, 0.0497, 0.1780]],

        [[0.3011, 0.1893, 0.9186, 0.2131],
         [0.3957, 0.6017, 0.4234, 0.5224],
         [0.4175, 0.0340, 0.9157, 0.3079]]])

In [32]:
# can change shape in any permutation
# pass col row no
f = f.permute(2,1,0)
f

tensor([[[0.0103, 0.3011],
         [0.9141, 0.3957],
         [0.2243, 0.4175]],

        [[0.9516, 0.1893],
         [0.7668, 0.6017],
         [0.8935, 0.0340]],

        [[0.2855, 0.9186],
         [0.1659, 0.4234],
         [0.0497, 0.9157]],

        [[0.2324, 0.2131],
         [0.4393, 0.5224],
         [0.1780, 0.3079]]])

In [33]:
f.shape

torch.Size([4, 3, 2])

##Tensor operation on GPU

In [34]:
torch.cuda.is_available()

True

In [35]:
device = torch.device('cuda')

In [36]:
# creating tensor on gpu

torch.rand((3,4), device =device)

tensor([[0.3563, 0.0303, 0.7088, 0.2009],
        [0.0224, 0.9896, 0.3737, 0.0823],
        [0.2851, 0.4433, 0.2989, 0.4175]], device='cuda:0')

In [37]:
# moving existing tensors to gpu
a1

tensor([[5, 6, 7],
        [3, 4, 6]])

In [38]:
u = a1.to(device)

In [39]:
u + 3

tensor([[ 8,  9, 10],
        [ 6,  7,  9]], device='cuda:0')

In [40]:
import time

#large size for performance comparision
size = 10000 # size of matrices

mat1_cpu = torch.randn(size, size)
mat2_cpu = torch.randn(size, size)

start_time = time.time()
ans_cpu = torch.matmul(mat1_cpu, mat2_cpu)
cpu_time = time.time() - start_time

print(f"time on cpu = {cpu_time}")


mat1_gpu = mat1_cpu.to('cuda')
mat2_gpu = mat2_cpu.to('cuda')

# measure time on gpu
start_time = time.time()
ans_gpu = torch.matmul(mat1_gpu, mat2_gpu)
torch.cuda.synchronize()  # ensure all gpu operations are complete
gpu_time = time.time() - start_time

print(f"time on gpu = {gpu_time}")

time on cpu = 16.09262442588806
time on gpu = 0.6993536949157715


In [42]:
# un squeeze
# ek given pos pe naya dim add karta hai
# used to convert image batches
img = torch.rand(226,226,3)
img.unsqueeze_(1).shape

torch.Size([226, 1, 226, 3])

In [49]:
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

## **NumPy & PyTorch**

In [50]:
import numpy as np

In [52]:
a = torch.tensor([1,2,3])
b = a.numpy()

print(type(b))
print(type(a))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [54]:
a = np.arange(21)
b = torch.from_numpy(a)

print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
